[theme]

# Background color for the main content area
backgroundColor = 'white'

# Color used for almost all text
textColor = 'black'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F3F4F6'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif" 
